---------------------------------------------
---------------------------------------------
----    File : config.weapons.lua        ----
----    Edited : gassastsina     		 ----
----	Side : client/server 	 		 ----
----    Description : ESX Weapons Config ----
---------------------------------------------
---------------------------------------------

Config.Weapons = {
  { name = 'WEAPON_KNIFE', label = _U('weapon_knife'), weight = 100 },
  { name = 'WEAPON_NIGHTSTICK', label = _U('weapon_nightstick'), weight = 100 },
  { name = 'WEAPON_HAMMER', label = _U('weapon_hammer'), weight = 100 },
  { name = 'WEAPON_BAT', label = _U('weapon_bat'), weight = 100 },
  { name = 'WEAPON_GOLFCLUB', label = _U('weapon_golfclub'), weight = 100 },
  { name = 'WEAPON_CROWBAR', label = _U('weapon_crowbar'), weight = 100 },
  { name = 'WEAPON_PISTOL', label = _U('weapon_pistol'), weight = 100 },
  { name = 'WEAPON_COMBATPISTOL', label = _U('weapon_combatpistol'), weight = 100 },
  { name = 'WEAPON_APPISTOL', label = _U('weapon_appistol'), weight = 100 },
  { name = 'WEAPON_PISTOL50', label = _U('weapon_pistol50'), weight = 100 },
  { name = 'WEAPON_MICROSMG', label = _U('weapon_microsmg'), weight = 100 },
  { name = 'WEAPON_SMG', label = _U('weapon_smg'), weight = 100  },
  { name = 'WEAPON_ASSAULTSMG', label = _U('weapon_assaultsmg'), weight = 100 },
  { name = 'WEAPON_ASSAULTRIFLE', label = _U('weapon_assaultrifle'), weight = 100 },
  { name = 'WEAPON_CARBINERIFLE', label = _U('weapon_carbinerifle'), weight = 100 },
  { name = 'WEAPON_ADVANCEDRIFLE', label = _U('weapon_advancedrifle'), weight = 100 },
  { name = 'WEAPON_MG', label = _U('weapon_mg'), weight = 100 },
  { name = 'WEAPON_COMBATMG', label = _U('weapon_combatmg'), weight = 100 },
  { name = 'WEAPON_PUMPSHOTGUN', label = _U('weapon_pumpshotgun'), weight = 100 },
  { name = 'WEAPON_SAWNOFFSHOTGUN', label = _U('weapon_sawnoffshotgun'), weight = 100 },
  { name = 'WEAPON_ASSAULTSHOTGUN', label = _U('weapon_assaultshotgun'), weight = 100 },
  { name = 'WEAPON_BULLPUPSHOTGUN', label = _U('weapon_bullpupshotgun'), weight = 100 },
  { name = 'WEAPON_STUNGUN', label = _U('weapon_stungun'), weight = 100 },
  { name = 'WEAPON_SNIPERRIFLE', label = _U('weapon_sniperrifle'), weight = 100 },
  { name = 'WEAPON_HEAVYSNIPER', label = _U('weapon_heavysniper'), weight = 100 },
  { name = 'WEAPON_REMOTESNIPER', label = _U('weapon_remotesniper'), weight = 100 },
  { name = 'WEAPON_GRENADELAUNCHER', label = _U('weapon_grenadelauncher'), weight = 100 },
  { name = 'WEAPON_RPG', label = _U('weapon_rpg'), weight = 100 },
  { name = 'WEAPON_STINGER', label = _U('weapon_stinger'), weight = 100 },
  { name = 'WEAPON_MINIGUN', label = _U('weapon_minigun'), weight = 100 },
  { name = 'WEAPON_GRENADE', label = _U('weapon_grenade'), weight = 100 },
  { name = 'WEAPON_STICKYBOMB', label = _U('weapon_stickybomb'), weight = 100 },
  { name = 'WEAPON_SMOKEGRENADE', label = _U('weapon_smokegrenade'), weight = 100 },
  { name = 'WEAPON_BZGAS', label = _U('weapon_bzgas'), weight = 100 },
  { name = 'WEAPON_MOLOTOV', label = _U('weapon_molotov'), weight = 100 },
  { name = 'WEAPON_FIREEXTINGUISHER', label = _U('weapon_fireextinguisher'), weight = 100 },
  { name = 'WEAPON_PETROLCAN', label = _U('weapon_petrolcan'), weight = 100 },
  { name = 'WEAPON_DIGISCANNER', label = _U('weapon_digiscanner'), weight = 100 },
  { name = 'WEAPON_BALL', label = _U('weapon_ball'), weight = 100 },
  { name = 'WEAPON_SNSPISTOL', label = _U('weapon_snspistol'), weight = 100 },
  { name = 'WEAPON_BOTTLE', label = _U('weapon_bottle'), weight = 100 },
  { name = 'WEAPON_GUSENBERG', label = _U('weapon_gusenberg'), weight = 100 },
  { name = 'WEAPON_SPECIALCARBINE', label = _U('weapon_specialcarbine'), weight = 100 },
  { name = 'WEAPON_HEAVYPISTOL', label = _U('weapon_heavypistol'), weight = 100 },
  { name = 'WEAPON_BULLPUPRIFLE', label = _U('weapon_bullpuprifle'), weight = 100 },
  { name = 'WEAPON_DAGGER', label = _U('weapon_dagger'), weight = 100 },
  { name = 'WEAPON_VINTAGEPISTOL', label = _U('weapon_vintagepistol'), weight = 100 },
  { name = 'WEAPON_FIREWORK', label = _U('weapon_firework'), weight = 100 },
  { name = 'WEAPON_MUSKET', label = _U('weapon_musket'), weight = 100 },
  { name = 'WEAPON_HEAVYSHOTGUN', label = _U('weapon_heavyshotgun'), weight = 100 },
  { name = 'WEAPON_MARKSMANRIFLE', label = _U('weapon_marksmanrifle'), weight = 100 },
  { name = 'WEAPON_HOMINGLAUNCHER', label = _U('weapon_hominglauncher'), weight = 100 },
  { name = 'WEAPON_PROXMINE', label = _U('weapon_proxmine'), weight = 100 },
  { name = 'WEAPON_SNOWBALL', label = _U('weapon_snowball'), weight = 100 },
  { name = 'WEAPON_FLAREGUN', label = _U('weapon_flaregun'), weight = 100 },
  { name = 'WEAPON_GARBAGEBAG', label = _U('weapon_garbagebag'), weight = 100 },
  { name = 'WEAPON_HANDCUFFS', label = _U('weapon_handcuffs'), weight = 100 },
  { name = 'WEAPON_COMBATPDW', label = _U('weapon_combatpdw'), weight = 100 },
  { name = 'WEAPON_MARKSMANPISTOL', label = _U('weapon_marksmanpistol'), weight = 100 },
  { name = 'WEAPON_KNUCKLE', label = _U('weapon_knuckle'), weight = 100 },
  { name = 'WEAPON_HATCHET', label = _U('weapon_hatchet'), weight = 100 },
  { name = 'WEAPON_RAILGUN', label = _U('weapon_railgun'), weight = 100 },
  { name = 'WEAPON_MACHETE', label = _U('weapon_machete'), weight = 100 },
  { name = 'WEAPON_MACHINEPISTOL', label = _U('weapon_machinepistol'), weight = 100 },
  { name = 'WEAPON_SWITCHBLADE', label = _U('weapon_switchblade'), weight = 100 },
  { name = 'WEAPON_REVOLVER', label = _U('weapon_revolver'), weight = 100 },
  { name = 'WEAPON_DBSHOTGUN', label = _U('weapon_dbshotgun'), weight = 100 },
  { name = 'WEAPON_COMPACTRIFLE', label = _U('weapon_compactrifle'), weight = 100 },
  { name = 'WEAPON_AUTOSHOTGUN', label = _U('weapon_autoshotgun'), weight = 100 },
  { name = 'WEAPON_BATTLEAXE', label = _U('weapon_battleaxe'), weight = 100 },
  { name = 'WEAPON_COMPACTLAUNCHER', label = _U('weapon_compactlauncher'), weight = 100 },
  { name = 'WEAPON_MINISMG', label = _U('weapon_minismg'), weight = 100 },
  { name = 'WEAPON_PIPEBOMB', label = _U('weapon_pipebomb'), weight = 100 },
  { name = 'WEAPON_POOLCUE', label = _U('weapon_poolcue'), weight = 100 },
  { name = 'WEAPON_WRENCH', label = _U('weapon_wrench'), weight = 100 },
  { name = 'WEAPON_FLASHLIGHT', label = _U('weapon_flashlight'), weight = 100 },
  { name = 'GADGET_NIGHTVISION', label = _U('gadget_nightvision'), weight = 100 },
  { name = 'GADGET_PARACHUTE', label = _U('gadget_parachute'), weight = 100 },
  { name = 'WEAPON_FLARE', label = _U('weapon_flare'), weight = 100 }, 
  { name = 'WEAPON_SNSPISTOL_MK2', label = _U('weapon_snspistol_mk2'), weight = 100 }, 
  { name = 'WEAPON_REVOLVER_MK2', label = _U('weapon_revolver_mk2'), weight = 100 },  
  { name = 'WEAPON_DOUBLEACTION', label = _U('weapon_doubleaction'), weight = 100 },    
  { name = 'WEAPON_SPECIALCARBINE_MK2', label = _U('weapon_specialcarabine_mk2'), weight = 100 },  
  { name = 'WEAPON_BULLPUPRIFLE_MK2', label = _U('weapon_bullpruprifle_mk2'), weight = 100 },   
  { name = 'WEAPON_PUMPSHOTGUN_MK2', label = _U('weapon_pumpshotgun_mk2'), weight = 100 },
  { name = 'WEAPON_MARKSMANRIFLE_MK2', label = _U('weapon_marksmanrifle_mk2'), weight = 100 },  
  { name = 'WEAPON_ASSAULTRIFLE_MK2', label = _U('weapon_assaultrifle_mk2'), weight = 100 },
  { name = 'WEAPON_CARBINERIFLE_MK2', label = _U('weapon_carbinerifle_mk2'), weight = 100 },  
  { name = 'WEAPON_COMBATMG_MK2', label = _U('weapon_combatmg_mk2'), weight = 100 },   
  { name = 'WEAPON_HEAVYSNIPER_MK2', label = _U('weapon_heavysniper_mk2'), weight = 100 },   
  { name = 'WEAPON_PISTOL_MK2', label = _U('weapon_pistol_mk2'), weight = 100 },   
  { name = 'WEAPON_SMG_MK2', label = _U('weapon_smg_mk2'), weight = 100 },
}
